# Generated by Django 5.2.6 on 2025-09-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='examle@gmail.com', max_length=254, unique=True),
        ),
    ]
