# Generated by Django 5.2.6 on 2025-09-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role_name',
            field=models.CharField(max_length=255),
        ),
    ]
