# Generated by Django 5.2.6 on 2025-09-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gmail_app_password_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
